### ISSUE TITLE
关于 vcc 供电问题

### ISSUE THREAD

**Issue by AyanamReiIV** [DT5EDU/i2c_oled#1]
原程序没有使用 3V3 供电而是设置了另一针脚输出高电平（为了不用接线直接插 oled），可能会出现刷新屏幕只刷新一半或者完全黑屏的问题（目前还不清楚是否是我的板子的问题），改变针脚 3V3 供电之后可以解决

**Comment by nep-0** [comment]
感谢反馈。`README.md` 将对此问题作出说明。

**Comment by 404-UnknownUsername** [comment]
是的，我也遇到了同样的问题，但是拔掉连接线重新插好之后可以解决这个问题。感谢指出！
